title: 尼叠再辞的学习笔记
description: 个人乱记
url: "https://xianlilun.github.io"
theme: minima
banner: "/assets/banner.jpg"
<div class="banner" style="position: relative;">
    <img src="{{ site.banner | relative_url }}" alt="横幅图" style="width: 100%; height: auto;" />
    <h1 style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); color: blue;">
        {{ page.title }}
    </h1>
</div>
nav:
  - title: "首页"
    url: "/"
  - title: "关于"
    url: "/about"


# Build settings
theme: minima
plugins:
  - jekyll-feed

