# 网站配置

# 导入主题
theme: jekyll-theme-chirpy

# 网页语言 › http://www.lingoes.net/en/translator/langcode.htm
lang: zh-CN

# 修改为你的时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: 尼爹再辞 # 主标题

tagline: 学习笔记记录 # 副标题

description: >- # 用于 SEO 元数据和 Atom Feed
  用于记录自己折腾的事情。

# 填写网站的协议和主机名。
# 例如 'https://username.github.io'，注意不要以 '/' 结尾。
url: "https://xianlilun.github.io"

github:
  username: xianlilun # 修改为你的 GitHub 用户名

twitter:
  username: twitter_username # 修改为你的 Twitter 用户名

social:
  name: 尼爹 # 更改为你的全名
  email: shuicenwudi@gmail.com # 修改为你的邮箱地址
  links:
    - https://github.com/xianlilun # 修改为你的 GitHub 主页
    - https://twitter.com/username # 修改为你的 Twitter 主页

# 网站验证设置
webmaster_verifications:
  google: # 填写你的 Google 验证码
  bing: # 填写你的 Bing 验证码
  alexa: # 填写你的 Alexa 验证码
  yandex: # 填写你的 Yandex 验证码
  baidu: # 填写你的百度验证代码
  facebook: # 填写你的 Facebook 验证代码

# ↑ --------------------------
# jekyll-seo-tag 设置结束

# 网站分析设置
analytics:
  google:
    id: # 填写你的 Google Analytics ID
  goatcounter:
    id: xianlilun  # 填写你的 GoatCounter ID
  umami:
    id: # 填写你的 Umami ID
    domain: # 填写你的 Umami 域名
  matomo:
    id: # 填写你的 Matomo ID
    domain: # 填写你的 Matomo 域名
  cloudflare:
    id: # 填写你的 Cloudflare 网站分析令牌
  fathom:
    id: # 填写你的 Fathom 网站 ID

# 页面浏览量设置
pageviews:
  provider: goatcounter # 目前仅支持 'goatcounter'

# 颜色方案偏好设置
theme_mode: # [light | dark]

# 媒体资源的 CDN 端点
cdn: "https://cdn.jsdelivr.net/gh/xianlilun/xianlilun.github.io@main"  #https://chirpy-img.netlify.app

# 侧边栏头像，支持本地或 CORS 资源
avatar: "assets/尼爹.jpg"

# 网站范围内的社交预览图像，用于 SEO `og:image` 元标签。
social_preview_image: "assets/尼爹.jpg" # 字符串，本地或 CORS 资源

# 布局中 TOC 的全局开关
toc: true

comments:
  provider: utterances # [disqus | utterances | giscus]
  disqus:
    shortname: # 填写 Disqus 短名称
  utterances:
    repo: xianlilun/xianlilun.github.io  # <gh-username>/<repo>
    issue_term: title # <url | pathname | title | ...>
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # 可选，默认为 'pathname'
    strict: # 可选，默认为 '0'
    input_position: # 可选，默认为 'bottom'
    lang: # 可选，默认为 `site.lang`
    reactions_enabled: # 可选，默认为 '1'

# 自托管静态资源，选填
assets:
  self_host:
    enabled: true # 布尔值，空表示 false
    env: # [development | production]

pwa:
  enabled: true # PWA 特性（可安装）的选项
  cache:
    enabled: true # PWA 离线缓存的选项
    deny_paths:
      # - "/example"  # 匹配 `<SITE_URL>/example/*` 的 URLs 将不会被 PWA 缓存

paginate: 10

# 网站的基本 URL
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge 选项
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
